# Generated by Django 4.2.19 on 2025-02-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='CORRECT_ANSWER',
            field=models.SmallIntegerField(help_text='Correct Answer Choice'),
        ),
    ]
