# Generated by Django 5.1.6 on 2025-02-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_question_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='SUBTOPIC_NAME',
            field=models.CharField(default='test', help_text='Sub topic name', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='QUESTION_NAME',
            field=models.TextField(help_text='Question Text'),
        ),
        migrations.AlterField(
            model_name='user_question',
            name='ANSWERED_ON',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp For the last Time Question was Sent to the user', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('TOPIC_NAME', 'SUBTOPIC_NAME', 'SUBJECT')},
        ),
    ]
