# Generated by Django 5.1.6 on 2025-02-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_question_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='SUBTOPIC_NAME',
            field=models.CharField(default='test', help_text='Sub topic name', max_length=1000),
        ),
        migrations.AlterField(
            model_name='topic',
            name='TOPIC_NAME',
            field=models.CharField(help_text='Name of the topic', max_length=1000),
        ),
    ]
