# Generated by Django 4.2.25 on 2025-10-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_question_question_id_alter_topic_topic_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('ALLERGEN_ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(help_text='Name of the allergen (e.g., Pollen, Peanuts)', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('LOG_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DATE', models.DateField(auto_now_add=True, help_text='The date the log entry was created')),
                ('HAS_ALLERGIES', models.BooleanField(default=False, help_text='Does the user have allergy symptoms?')),
                ('HAS_COUGH', models.BooleanField(default=False, help_text='Does the user have a cough?')),
                ('FOOD', models.JSONField(blank=True, default=list, help_text='List of food items consumed')),
                ('ALLERGENS', models.ManyToManyField(blank=True, help_text='Specific allergens the user was exposed to', to='Users.allergen')),
            ],
        ),
    ]
